### ISSUE TITLE
Not working on Wordpress 4.5.1 with ACF Pro

### ISSUE THREAD

**Issue by will83** [toszcze/acf-date-time-picker#1]
The console show this : 
<img width="634" alt="capture d ecran 2016-04-30 a 10 11 11" src="https://cloud.githubusercontent.com/assets/804476/14934776/03bfceb6-0ebc-11e6-95ce-f36aa53f0f96.png">
Thank you !

**Comment by toszcze** [comment]
I'm using this plugin on few websites (WP 4.5.1 and ACF 5) and I didn't notice any issues. So I need more information.
What other plugins do you have installed? Could you please test the plugin without any other plugins activated (activate only ACF and Date Time Picker)?

Thank you.

**Comment by toszcze** [comment]
One more question. ;)
What other fields are you using in this field group?

**Comment by will83** [comment]
You can find a screenshot attached.
I don’t use any other plugins (juste plugins made by me to add new custom post types… without javascript).

Thank you

De : Bartosz Romanowski <notifications@github.com>
Répondre à : toszcze/acf-date-time-picker <reply@reply.github.com>
Date : samedi 30 avril 2016 10:36
À : toszcze/acf-date-time-picker <acf-date-time-picker@noreply.github.com>
Cc : William Ode <wode@declik.com>, Author <author@noreply.github.com>
Objet : Re: [toszcze/acf-date-time-picker] Not working on Wordpress 4.5.1 with ACF Pro (#1)


One more question. ;)
What other fields are you using in this field group?

**Comment by toszcze** [comment]
I think you forgot to attach the screenshot. ;)

**Comment by will83** [comment]
No, I had well put the attachment... weired :-)
Here is a link to this capture : https://www.dropbox.com/s/x6gltg73g3njwls/Capture%20d%E2%80%99%C3%A9cran%202016-04-30%20%C3%A0%2010.36.51.png?dl=0


De : Bartosz Romanowski <notifications@github.com>
Répondre à : toszcze/acf-date-time-picker <reply@reply.github.com>
Date : samedi 30 avril 2016 10:44
À : toszcze/acf-date-time-picker <acf-date-time-picker@noreply.github.com>
Cc : William Ode <wode@declik.com>, Author <author@noreply.github.com>
Objet : Re: [toszcze/acf-date-time-picker] Not working on Wordpress 4.5.1 with ACF Pro (#1)


I think you forgot to attach the screenshot. ;)

**Comment by toszcze** [comment]
Thanks. :) But I would need the screenshot of the field group configuration (to check what field types you are using).

**Comment by will83** [comment]
The config : https://www.dropbox.com/s/wycgn0r49cuszhl/Capture%20d%E2%80%99%C3%A9cran%202016-04-30%20%C3%A0%2010.50.31.png?dl=0

De : Bartosz Romanowski <notifications@github.com>
Répondre à : toszcze/acf-date-time-picker <reply@reply.github.com>
Date : samedi 30 avril 2016 10:48
À : toszcze/acf-date-time-picker <acf-date-time-picker@noreply.github.com>
Cc : William Ode <wode@declik.com>, Author <author@noreply.github.com>
Objet : Re: [toszcze/acf-date-time-picker] Not working on Wordpress 4.5.1 with ACF Pro (#1)


Thanks. :) But I would need the screenshot of the field group configuration (to check what field types you are using).

**Comment by toszcze** [comment]
I am really sorry, but I am not able to re-create this issue on my end. I created exactly the same field group and I didn't notice any issues. I'm using WP 4.5.1 and ACF 5.3.7.

**Comment by will83** [comment]
Exactly the same for me…
And it doesn’t work in both Chrome and Firefox (so the problem don’t came from a Chrome Plugin).
The only thing I can see, I this error in the console (for both Chrome and Firefox) : https://www.dropbox.com/s/fki1fi1mfreksc5/Capture%20d%E2%80%99%C3%A9cran%202016-04-30%20%C3%A0%2011.08.26.png?dl=0

De : Bartosz Romanowski <notifications@github.com>
Répondre à : toszcze/acf-date-time-picker <reply@reply.github.com>
Date : samedi 30 avril 2016 11:03
À : toszcze/acf-date-time-picker <acf-date-time-picker@noreply.github.com>
Cc : William Ode <wode@declik.com>, Author <author@noreply.github.com>
Objet : Re: [toszcze/acf-date-time-picker] Not working on Wordpress 4.5.1 with ACF Pro (#1)


I am really sorry, but I am not able to re-create this issue on my end. I created exactly the same field group and I didn't notice any issues. I'm using WP 4.5.1 and ACF 5.3.7.

**Comment by toszcze** [comment]
It looks like a problem with jQuery and/or jQuery UI. I still was not able to re-create this issue on my end, but please replace '/wp-content/plugins/acf-date-time-picker/assets/js/jquery-ui-timepicker/jquery-ui-timepicker-addon.min.js' file with [this one](https://dl.dropboxusercontent.com/u/2600317/jquery-ui-timepicker-addon.min.js) and let me know if it helps.

**Comment by will83** [comment]
I’ve modify the file but it continues to not working.
Do you want a temporary access to my backend ?
I do not want to bother with a problem that concerns only me probably.


De : Bartosz Romanowski <notifications@github.com>
Répondre à : toszcze/acf-date-time-picker <reply@reply.github.com>
Date : samedi 30 avril 2016 11:49
À : toszcze/acf-date-time-picker <acf-date-time-picker@noreply.github.com>
Cc : William Ode <wode@declik.com>, Author <author@noreply.github.com>
Objet : Re: [toszcze/acf-date-time-picker] Not working on Wordpress 4.5.1 with ACF Pro (#1)


It looks like a problem with jQuery and/or jQuery UI. I still was not able to re-create this issue on my end, but please replace '/wp-content/plugins/acf-date-time-picker/assets/js/jquery-ui-timepicker/jquery-ui-timepicker-addon.min.js' file with this one<https://dl.dropboxusercontent.com/u/2600317/jquery-ui-timepicker-addon.min.js> and let me know if it helps.

**Comment by toszcze** [comment]
Yes, that would be great - thank you. Please send login details to bartosz@romanowski.im.

**Comment by will83** [comment]
It’s done, please tell me when I can disable this access.
The custom post type : http://preprod.sebastien-martinez.com/wp-admin/edit.php?post_type=formation-date
The ACF group : http://preprod.sebastien-martinez.com/wp-admin/post.php?post=30&action=edit

Thank you

De : Bartosz Romanowski <notifications@github.com>
Répondre à : toszcze/acf-date-time-picker <reply@reply.github.com>
Date : samedi 30 avril 2016 12:05
À : toszcze/acf-date-time-picker <acf-date-time-picker@noreply.github.com>
Cc : William Ode <wode@declik.com>, Author <author@noreply.github.com>
Objet : Re: [toszcze/acf-date-time-picker] Not working on Wordpress 4.5.1 with ACF Pro (#1)


Yes, that would be great - thank you. Please send login details to bartosz@romanowski.im<mailto:bartosz@romanowski.im>.

**Comment by toszcze** [comment]
I can see you are using jQuery 2.1.x, so at the moment there are two jQuery versions loaded at a time. Could you please remove jQuery 2.1, so we can check if this is a cause of this issue? I don't know which part of your website is loading it.

**Comment by will83** [comment]
You’re right. It’s a line in my functions.php file that include this version of Jquery… but not only for the frontend. I’ve repaired this with a if ( ! is_admin() ) {
It’s working now.
Thank you very much for this help and long life for your plugin.

De : Bartosz Romanowski <notifications@github.com>
Répondre à : toszcze/acf-date-time-picker <reply@reply.github.com>
Date : samedi 30 avril 2016 12:25
À : toszcze/acf-date-time-picker <acf-date-time-picker@noreply.github.com>
Cc : William Ode <wode@declik.com>, Author <author@noreply.github.com>
Objet : Re: [toszcze/acf-date-time-picker] Not working on Wordpress 4.5.1 with ACF Pro (#1)


I can see you are using jQuery 2.1.x, so at the moment there are two jQuery versions loaded at a time. Could you please remove jQuery 2.1, so we can check if this is a cause of this issue? I don't know which part of your website is loading it.

**Comment by toszcze** [comment]
I'm glad I could help. :)
